### PR TITLE
Jad deletepost

### PR DESCRIPTION
**Pull request by JAndraeis53**
Completed the delete functionality for post
post can be deleted from MyPost view and Details view
post delete has confirmation page
delete rejection returns to post details view

### CODE REVIEW

**Comment by IanJames2** [comment]
Delete works in My Posts, but not in Posts

**Review by IanJames2 — APPROVED** [review]
👍🏾

**Comment by dparsley1203** [comment]
Able to delete post I created

**Comment by JAndraeis53** [comment]
👍🏾

**Pull request merged**
